title: Bisq
baseurl: ""
url: "https://bisq.network"
markdown: kramdown
permalink: /blog/:title/
livereload: true
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin
languages:
  - cn
  - en
exclude_from_localizations:
  - javascript
  - images
  - css
  - js
  - press-material
  - favicon.ico
feed:
  path: blog/feed.atom
include:
  - _redirects
exclude:
  - CNAME
  - README
  - Gemfile
  - vendor
