version: "2"

services:
  website:
    container_name: bsiq
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
#    ports:
#      - 4000:4000
#      - 35729:35729
#      - 3000:3000
#      -   80:4000
    networks:
       - nginx-proxy
    environment:
     - VIRTUAL_HOST=bisq.cn
     - VIRTUAL_PORT=4000
     - LETSENCRYPT_HOST=bisq.cn,www.bisq.cn
     - LETSENCRYPT_EMAIL=keol95173@msn.com

networks:
  nginx-proxy:
   external:
      name: nginx-proxy
